In [1]:
import numpy as np

In [2]:
list_int = [8, 3, 34, 111]

In [3]:
a_int = np.array(list_int)
a_int

array([  8,   3,  34, 111])

In [4]:
a_int.ndim

1

In [5]:
a_int.shape

(4,)

In [6]:
a_mix = np.array([[1, 2.0], [0, 0],(5.78, 3.)])
a_mix

array([[ 1.  ,  2.  ],
       [ 0.  ,  0.  ],
       [ 5.78,  3.  ]])

In [7]:
a_mix.ndim

2

In [8]:
a_mix.shape

(3, 2)

In [9]:
a_mix.dtype

dtype('float64')

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(.4, 1.1, 7)

array([ 0.4       ,  0.51666667,  0.63333333,  0.75      ,  0.86666667,
        0.98333333,  1.1       ])

In [12]:
np.random.randn(2,3)

array([[ 1.00008745, -0.18434797,  0.19025243],
       [ 0.87651653, -0.77215155,  0.79458797]])

In [13]:
np.ones(2,3,4,5)

TypeError: ones() takes from 1 to 3 positional arguments but 4 were given

In [14]:
np.ones(2,3,5)

TypeError: data type not understood

In [16]:
np.ones((3,4,7), dtype = np.int64)

array([[[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]]], dtype=int64)

In [17]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [19]:
a[2:6]

array([3, 4, 5, 6])

In [20]:
a_view = a[3:5]

In [21]:
a_view

array([4, 5])

In [22]:
a_view[:] = 234

In [23]:
a_view

array([234, 234])

In [24]:
x1 = np.arange(4)

In [25]:
x1

array([0, 1, 2, 3])

In [26]:
x2 = x1.reshape(4,1)

In [27]:
x2

array([[0],
       [1],
       [2],
       [3]])

In [28]:
y = np.ones(5)

In [29]:
y

array([ 1.,  1.,  1.,  1.,  1.])

In [30]:
xy = x2 * y

In [31]:
xy

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.]])